### ISSUE TITLE
/profile doesnt check for a cookie

### ISSUE THREAD

**Issue by thermobased** [thermobased/flask-webapp#3]
```flask --app main run                                                                                                                               ✔  flask-project  
 * Serving Flask app 'main'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
[2024-04-12 12:54:34,303] ERROR in app: Exception on /profile [GET]
Traceback (most recent call last):
  File "/home/dog/WebstormProjects/flask-project/venv/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dog/WebstormProjects/flask-project/venv/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dog/WebstormProjects/flask-project/venv/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dog/WebstormProjects/flask-project/venv/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dog/WebstormProjects/flask-project/main.py", line 176, in profile
    user = welcome[0]
           ~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by thermobased** [comment]
fixed by 880f45e
